feat: use github edgee action (#5)
* feat: use github edgee action

* feat: add verification

* feat: change order of steps

* feat: add ls

* feat: change - to °

* feat: typo in readme

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -1,27 +1,36 @@
 name: Check
 on:
-  push:
-    branches:
-      - main
-  pull_request:
+    push:
+        branches:
+            - main
+    pull_request:
 
 jobs:
-  test:
-    name: test
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+    test:
+        name: test
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v4
 
-      - name: "Set up Dotnet SDK"
-        run: |
-            sudo apt-get update
-            sudo apt-get install software-properties-common -y
-            sudo add-apt-repository ppa:dotnet/backports
-            sudo apt-get update
-            sudo apt-get install dotnet-sdk-9.0 -y
+            - name: "Set up Dotnet SDK"
+              run: |
+                  sudo apt-get update
+                  sudo apt-get install software-properties-common -y
+                  sudo add-apt-repository ppa:dotnet/backports
+                  sudo apt-get update
+                  sudo apt-get install dotnet-sdk-9.0 -y
 
-      - name: Build component
-        run: |
-            dotnet build
+            - name: Install edgee
+              uses: edgee-cloud/install-edgee-cli@v0.1.0
 
+            - name: Build component
+              run: |
+                  edgee components build
+
+            - name: Verify .wasm file exists
+              run: |
+                  if [ ! -f "./dc_component.wasm" ]; then
+                    echo "❌ Error: dc_component.wasm not found" >&2
+                    exit 1
+                  fi
